---
  - hosts: localhost
    connection: local
    tasks:

    - name: Check url status and set new_status var
      uri:
        url: "{{ url_to_test }}"
      register: result
      ignore_errors: yes
    - set_fact:
        new_status: "{{ '1' if (result.status == 200) else '4' }}"

    - name: Get component details and set current_status var
      uri:
        url: "{{ cachet_url }}/api/v1/components/{{ component_id }}"
        method: GET
      register: details
    - set_fact:
        current_status: "{{ details.json.data.status }}"

    - name: Update component status to new_status IF current != new
      uri:
        url: "{{ cachet_url }}/api/v1/components/{{ component_id }}"
        method: PUT
        body: " {\"status\": \"{{ new_status }}\" }"
        return_content: yes
        headers:
          X-Cachet-Token: "{{ API_token }}"
          Content-Type: application/json
        body_format: json
      when: 'current_status != new_status'
